spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/ClinicM_S
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format-sql: true
  mail:
   host: smtp.gmail.com
   port: 587
   username: harishantarkar3738@gmail.com
   password: jxqf zhon idtc wryd
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
   logging:
     level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind : TRACE			 		 		 		 